version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
       - name: product
         identifier: raw_gz_product
         description: product of greenweez
         columns
          - name: product_id
            description: primary key of the table
            tests:
              - unique
              - not_null
              
              
          - name: purchase_price
            description: the purchase price of the product 
       - name: sales
         identifier: raw_gz_sales
         description: sales of greenweez
         columns: 
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by customer to purchase the product
          - name: quantity
            description: the quantity of product purchased for this order
       - name: ship
         identifier: raw_gz_ship
         description: ship of greenweez
         columns :
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
              
              
          - name: shipping_fee
            description: the price customer pay for shipping
          - name: log_cost
            description: the cost of preparing parcel in the warehouse 
          - name: ship_cost
            description: the shipping cost paid by greenweez to the carrier or transporter



